openapi: 3.0.0
info:
  title: User Authentication API with Laravel
  description: API for user authentication and registration using the Laravel framework
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000
paths:
  /api/auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '401':
          description: Error invalid credentials
        '200':
          description: Success

  /api/auth/register:
    post:
      summary: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 5
                  maxLength: 100
                password_confirmation:
                  type: string
                  minLength: 5
                  maxLength: 100
      responses:
        '422':
          description: The password and password_confirmation do not match
        '201':
          description: Success

components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        password_confirmation:
          type: string
